version: '3'

services:
  # Next.js application
  inventsphere-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # Not exposing directly to host in production
    expose:
      - "3000"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  
  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Uncomment when you have SSL certificates
      # - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - inventsphere-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
